# Generated by Django 5.2.4 on 2025-07-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['title', 'lawyer', 'status'], name='myapp_case_title_ed6c11_idx'),
        ),
    ]
