# Generated by Django 5.2.4 on 2025-07-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_case_myapp_case_title_ed6c11_idx'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO myapp_Client (first_name, last_name, email, phone, birth_date) VALUES
            ('Alice', 'Johnson', 'alice.johnson@example.com', '555-1234', '1990-03-15'),
            ('Bob', 'Smith', 'bob.smith@example.com', '555-5678', '1985-07-22');

            """,
            """
            INSERT INTO myapp_Lawyer (first_name, last_name, email, phone, specialization) VALUES
            ('Sarah', 'Carter', 'sarah.carter@example.com', '555-0001', 'Criminal Law'),
            ('Michael', 'Lee', 'michael.lee@example.com', '555-0002', 'Corporate Law');
            """
        )
    ]
